name: Build and Push Multi-Arch Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push worker
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          file: worker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/juancristobal/video2md-worker:latest
            juancristoballisboa/video2md-worker:latest

      - name: Build and Push gateway
        uses: docker/build-push-action@v5
        with:
          context: .
          file: gateway/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/juancristobal/video2md-gateway:latest
            juancristoballisboa/video2md-gateway:latest

      - name: Build and Push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: frontend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/juancristobal/video2md-frontend:latest
            juancrristoballisboa/video2md-frontend:latest
